home_list/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

home_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from home_shop.views import register, login_user
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('about/',include('about.urls')),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('auth/', include('authentication.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('logout/', logout_user, name='logout'),
    path('tambah/<int:id>/', tambah_amount, name='tambah_amount'),
    path('kurang/<int:id>/', kurang_amount, name='kurang_amount'),
    path('hapus/<int:id>/', hapus_item, name='hapus_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-ajax/<int:id>/',delete_item_ajax,name='delete_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

class Item(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(default=datetime.now)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "description","amount"]

main/views.py
import json
from django.shortcuts import redirect, render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Item.objects.filter(user=request.user)
    total_item = 0
    for i in products:
        total_item += 1
    context = {
        'app_name':'Home Shop',
        'name': request.user.username,
        'class': 'PBP A',
        'products': products,
        'total_item': total_item,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('index'))
    response.delete_cookie('last_login')
    return response

def tambah_amount(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        item.amount += 1
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def kurang_amount(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        if item.amount > 0:
            item.amount -= 1
            item.save()
        if item.amount == 0:
            item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def hapus_item(request, id):
    if request.method == "POST":
        item = Item.objects.get(pk=id)
        item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Item(name=name, price=price, description=description, user=user, amount = amount)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def delete_item_ajax(request, id):
    if request.method == 'DELETE':
        Item.objects.get(pk=id).delete()
        return HttpResponse(b"DELETED", status = 201)
    return HttpResponseNotFound()

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
#this is a testing for doing

main/templates/create_product.html
{% extends 'base.html' %} 
{% load static %}   
{% block meta %}
<title>{{app_name}}</title>
<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'main/css/create.css' %}">
{% endblock meta %}

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
                <a href="/main" class="back-button">Go Back</a>
            </td>
        </tr>
    </table>
</form>


{% endblock %}

main/templates/main.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
<head>
    {% block meta %}
    <title>{{app_name}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}">
    <meta name="csrf-token" content="{{ csrf_token }}">
    {% endblock meta %}
</head>
<body>
    {% block content %}
    {%include "snippets/navbar.html"%}
    <div class="tugas">
        <h1>{{app_name}}'s Item</h1>
    </div>
    <div class="profil">
        <h5>App Name:</h5>
        <p>{{app_name}}</p>
        <h5>Name: </h5>
        <p>{{ name }}<p>
        <h5>Class: </h5>
        <p>{{ class }}<p>
    </div>
    
    <div class="table-container"> 
        <div class="centered-content">
            <h5 id="total_items">kamu menyimpan {{total_item}} item pada aplikasi ini</h5>
            <br>
            <div id="product_cards" class="row"></div>
            <h4>Sesi terakhir login: {{ last_login }}</h4>
            <div class="button-container">
                <a href="{% url 'main:create_product' %}" class="btn">Add New Product</a>
                <a href="{% url 'main:logout' %}" class="btn">Logout</a>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>  

    <script>

        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            
            const container = document.getElementById("product_cards");
            container.innerHTML = ""; // Clear the previous cards
            const products = await getProducts();
            
            const totalItemsText = document.querySelector('h5#total_items'); // Pastikan Anda memiliki elemen dengan id 'total_items'
            totalItemsText.textContent = `kamu menyimpan ${products.length} item pada aplikasi ini`;

            // Fetch CSRF token from meta tag
            let csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        
            let htmlString = "";
            products.forEach((item, index) => {
                // Every 3 items, add a row div
                if (index % 3 === 0) {
                    htmlString += `<div class="row">`;
                }
        
                let cardBackgroundColor = (index === products.length - 1) ? "orange" : "beige";
                let columnClass = products.length === 1 ? 'col-12' : 'col-lg-4 col-md-6';
                // Add the card inside a wider column with modified button layout and background color
                htmlString += `
                <div class="${columnClass} mb-4">
                    <div class="card" style="background-color: ${cardBackgroundColor}; max-height: 500px; overflow: auto;">
                        <div class="card-header">${item.fields.name}</div>
                        <div class="card-body">
                            <p><strong>Harga:</strong> ${item.fields.price}</p>
                            <p><strong>Date Added:</strong> ${item.fields.date_added}</p>
                            <p><strong>Description:</strong> ${item.fields.description}</p>
                            <p><strong>Amount:</strong> ${item.fields.amount}</p>
                            
                            <div class="row">
                                <div class="col-4">
                                    <form method="post" action="tambah/${item.pk}/">
                                        <input type="hidden" name="csrfmiddlewaretoken" value="${csrfToken}">
                                        <button type="submit" class="btn btn-light narrow-btn">+</button>
                                    </form>
                                </div>
                                
                                <div class="col-4">
                                    <form method="post" action="kurang/${item.pk}/">
                                        <input type="hidden" name="csrfmiddlewaretoken" value="${csrfToken}">
                                        <button type="submit" class="btn btn-light narrow-btn">-</button>
                                    </form>
                                </div>
        
                                <div class="col-4">
                                    <a><button onclick="deleteItem(${item.pk})" type="submit">Delete</button></a>
                                </div>
                            </div>
        
                        </div>
                    </div>
                </div>`;
        
                if (index % 3 === 2 || index === products.length - 1) {
                    htmlString += `</div>`;
                }
            });
        
            container.innerHTML = htmlString;
        }
        
        refreshProducts();
        
        
        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)
    
            document.getElementById("form").reset()

            return false
        }
        document.getElementById("button_add").onclick = addProduct

        async function deleteItem(id){
            let url="{% url 'main:delete_item_ajax' '999' %}";
            url=url.replace('999',id);
            const response =await fetch(url,{
                method: "DELETE",
            }).then(refreshProducts); 
        }
    </script>


    <br>
    <br>
    {%include "snippets/scripts.html"%}
    {% endblock content %}
</body>
</html> 